"""How much of a car's keeper history the Dutch register still shows: the censoring behind a self-registration check.

A dealer that registers a car in its own name and sells it on within weeks leaves a quick keeper change. The public
register keeps only the *current* keeper, so a later change hides it. How much is hidden depends on when the register
is read:

  1. **Years later.** The share of new cars first registered in 2021 and 2022 whose current keeper arrived more than
     30 days after first registration. For those cars any quick change is gone.
  2. **Promptly.** A ledger that reads the register soon after each quarter loses only the cars that changed keeper
     again in the meantime. The chance of a keeper change in a car's first three months, from the monthly hazard of
     `lease_end.py`, bounds that from above: it includes the quick changes themselves.

These feed the X1 self-registration detector (part 7b) as the censoring of its register source. Real RDW data,
counted server-side; nothing is synthetic.

Source: RDW open data, Gekentekende voertuigen (public domain), https://opendata.rdw.nl/resource/m9d7-ebf2.json
Usage: .venv/bin/python analysis/keeper_history.py   (after lease_end.py has cached its monthly table)
"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent))
from build_reference import rdw_group  # noqa: E402
from build_unified import MAKE_ALIASES, STELLANTIS, md_table, norm_name  # noqa: E402
from lease_end import WINDOWS, hazard, monthly  # noqa: E402

OUT = HERE / "keeper_history_report.md"
NEW = ("voertuigsoort='Personenauto' AND datum_eerste_tenaamstelling_in_nederland_dt = datum_eerste_toelating_dt "
       "AND datum_eerste_toelating_dt >= '{y}-01-01T00:00:00.000' AND datum_eerste_toelating_dt < '{z}-01-01T00:00:00.000'")
LATER = " AND date_diff_d(datum_tenaamstelling_dt, datum_eerste_toelating_dt) > 30"


def count(where):
    return int(rdw_group("count(1) AS n", where, "")["n"].iloc[0])


def main():
    makes = rdw_group("merk, count(1) AS n", "voertuigsoort='Personenauto'", "merk", limit=50_000)
    group = sorted(makes.loc[norm_name(makes["merk"]).replace(MAKE_ALIASES).isin(STELLANTIS), "merk"].unique())
    quoted = ",".join("'" + m.replace("'", "''") + "'" for m in group)
    rows = []
    for y in (2021, 2022):
        for label, extra in (("group brands", f" AND merk IN ({quoted})"), ("all brands", "")):
            where = NEW.format(y=y, z=y + 1) + extra
            n, later = count(where), count(where + LATER)
            rows.append({"cohort": f"{y} {label}", "new cars": f"{n:,}", "current keeper after 30 days": f"{later:,}",
                         "share hidden (%)": round(100 * later / n, 2)})
    late = pd.DataFrame(rows)

    d = monthly()
    recent = sorted(d["window"].dropna().unique())[-WINDOWS:]
    early = []
    for brands, label in (("all", "all domestic cars"), ("group", "the group's brands")):
        h = hazard(d, brands, recent)
        p = 1 - float(np.prod(1 - (h.loc[1:3, "n"] / h.loc[1:3, "parc"]).to_numpy()))
        early.append({"population": label, "keeper change within the first 3 months (%)": round(100 * p, 2)})
    early = pd.DataFrame(early)

    OUT.write_text(f"""# How much keeper history the register still shows

_Generated by `analysis/keeper_history.py`. Real RDW register data (public domain), not synthetic._

## Read years later: the share of new cars whose early keeper history is hidden

New cars first registered in the Netherlands (first admission = first Dutch registration) whose current keeper was
registered more than 30 days after first registration, as of the latest register. For these, a quick keeper change
after registration can no longer be seen.

{md_table(late)}

## Read promptly: the chance of a further change within three months

From the monthly keeper-change hazard of `lease_end.py` (the latest 12 months), the chance that a car changes keeper
in its first three months of age. A register read within a quarter of the event loses at most this share of quick
changes, and less, because the quick changes themselves are in it.

{md_table(early)}
""")
    print(md_table(late))
    print(md_table(early))
    print(f"wrote {OUT.relative_to(HERE.parent)}")


if __name__ == "__main__":
    main()
