"""X3 part 3: what drives the 48- and 60-month waves? The spike test of `lease_end.py`, brand by brand.

Two mechanisms can put a wave at 60 months in the Dutch register. A lease contract of 60 months ends (business
lease, or private lease, which is common for small cars in the Netherlands ~), and the car is sold on. Or the
company-car tax (bijtelling) rate, locked for 60 months from first registration, resets: an electric car registered
in 2018-21 on a low locked rate jumps to the current rate, so its driver swaps it. The tax lock predicts a much
larger wave in an all-electric brand driven as a company car (Tesla) than elsewhere. Lease ends predict a wave in
every brand that is leased, whatever the fuel. Brand is only a proxy: the open register table holds no fuel or buyer
type per car, and we have no sourced buyer mix by brand.

Same population, windows and test as `lease_end.py` (the latest 12 calendar months). Real RDW data, not synthetic.
Usage: .venv/bin/python analysis/lease_mechanism.py
"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent))
from build_reference import rdw_group  # noqa: E402
from build_unified import md_table  # noqa: E402
from lease_end import BORN_HERE, COHORT, CONTRACTS, LIVE, WINDOWS, excess, hazard  # noqa: E402

OUT = HERE / "lease_mechanism_report.md"
CACHE = HERE.parent / "data" / "x3_brand_hazard.parquet"
BRANDS = {"Tesla (all electric)": "TESLA", "Volkswagen": "VOLKSWAGEN", "Kia": "KIA", "Dacia": "DACIA",
          "Suzuki": "SUZUKI"}


def monthly_brands():
    if CACHE.exists():
        return pd.read_parquet(CACHE)
    latest = pd.Timestamp(rdw_group("max(datum_tenaamstelling_dt) AS m", LIVE, "")["m"].iloc[0])
    end = latest.normalize().replace(day=1)
    rows = []
    for label, merk in BRANDS.items():
        bw = f"{LIVE} AND {BORN_HERE} AND merk='{merk}'"
        parc = rdw_group(f"{COHORT} AS c, count(1) AS n", bw, "c", limit=50_000)
        rows.append(parc.assign(brands=label, kind="parc", window=pd.NaT))
        for i in range(1, WINDOWS + 1):
            w0, w1 = end - pd.DateOffset(months=i), end - pd.DateOffset(months=i - 1)
            moved = (f"{bw} AND datum_tenaamstelling_dt >= '{w0:%Y-%m-%d}T00:00:00.000' "
                     f"AND datum_tenaamstelling_dt < '{w1:%Y-%m-%d}T00:00:00.000' "
                     "AND datum_tenaamstelling_dt > datum_eerste_tenaamstelling_in_nederland_dt")
            m = rdw_group(f"{COHORT} AS c, count(1) AS n", moved, "c", limit=50_000)
            rows.append(m.assign(brands=label, kind="moved", window=w0))
        print(f"  {label}: done", flush=True)
    d = pd.concat(rows, ignore_index=True)
    d["c"], d["n"] = pd.to_datetime(d["c"]), pd.to_numeric(d["n"])
    d.to_parquet(CACHE, index=False)
    return d


def main():
    d = monthly_brands()
    rows = []
    for label in BRANDS:
        h = hazard(d, label)
        base = {a: excess(h, a) for a in range(12, 109)}
        row = {"brand": label, "cars on the road": f"{int(d[(d['brands'] == label) & (d['kind'] == 'parc')]['n'].sum()):,}",
               "keeper changes in the window": f"{int(h['n'].sum()):,}"}
        for k in CONTRACTS:
            e = base[k]
            others = np.array([v for a, v in base.items() if a != k and v is not None])
            row[f"{k} months: excess (%)"] = round(100 * e, 1) if e is not None else ""
            row[f"{k} months: placebo p"] = round(float(np.mean(others >= e)), 3) if e is not None else ""
        rows.append(row)
    t = pd.DataFrame(rows)
    OUT.write_text(f"""# X3 part 3: which cars make the 48- and 60-month waves?

_Generated by `analysis/lease_mechanism.py`. Real RDW register data (public domain), not synthetic._

The spike test of `lease_end.py` (ages k to k+2 against the local trend; the placebo p ranks it against every other age
from 12 to 108 months), run brand by brand on the same 12 calendar months. Tesla is all-electric, the one brand where
the company-car tax lock should dominate; the others sell mixes of fuels to mixes of buyers. Small brands have noisy
single-age hazards, so read the placebo p before the size.

{md_table(t)}
""")
    print(md_table(t))


if __name__ == "__main__":
    main()
