"""X1 part 7b: a gaming check built on the mechanism, designed on our world and validated on a holdout world.

Layer 3's statistical gaming rule (`gaming_suspects`) looks at the timing of registrations. It catches about half the
gamed dealer-quarters and most of what it flags is innocent, because a quarter-end bump is common and mostly honest.
The real register holds a better trace (`analysis/self_registration_report.md`): a dealer that registers a car in its
own name to reach a target passes it to the real buyer weeks later, so the car's keeper changes quickly.
`layer3_rules.self_registration_suspects` counts each car in the quarter its keeper took it on, when that came within
30 days of registration; a dealer-quarter that meets its target only on registration dates is a suspect.

The register source (`x1_register_keepers`, written by `inject.py`) is anchored on real RDW figures read from the
project register: the base rate and the quarter-end lift of quick keeper changes (all of it treated as legitimate,
the hard case), and the share of early changes a later change hides. Two reads of the register:
  prompt  within a quarter of the event, as a ledger polling the register would; few early changes hidden
  late    years later, as a one-off audit of the open register would; most early changes hidden

Worlds:
  ours (design)          the world the check was designed on; its parameters were fixed before the holdout existed
  holdout (fresh seed)   the same real cars, with new dealers, sales, claims and gaming (`X1_SEED_OFFSET=1000`)
  RT1, RT2               the red-team worlds, which contain no gaming of ours: every flag there is a false alarm
                         against gaming, and a sign of how the check behaves on another author's world

The unit is the A dealer-quarter, as a reviewer would see it. All figures are synthetic: they measure the tool, and the
check's precision depends on our assumed gaming rate. What carries over is the comparison with the timing rule.
Output: leak1/x1_selfreg_report.md
Usage: .venv/bin/python leak1/selfreg.py
"""
import sys
from pathlib import Path

import pandas as pd

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE))
import layer3_rules as k3  # noqa: E402

DATA = HERE.parent / "data"
OUT = HERE / "x1_selfreg_report.md"
WORLDS = [("ours (design)", "synthetic"), ("holdout (fresh seed)", "synthetic_holdout"),
          ("RT1", "synthetic_redteam"), ("RT2", "synthetic_redteam2")]


def table(header, rows):
    lines = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    return "\n".join(lines + ["| " + " | ".join(str(c) for c in r) + " |" for r in rows])


def main():
    rows = []
    for name, folder in WORLDS:
        w = DATA / folder
        master = k3.trusted_record(pd.read_parquet(w / "x1_master.parquet"), pd.read_parquet(w / "x1_oem_record.parquet"))
        targets = pd.read_parquet(w / "x1_targets.parquet")
        keepers = pd.read_parquet(w / "x1_register_keepers.parquet")
        truth = w / "x1_truth_cars.parquet"
        gamed = set()
        if folder in ("synthetic", "synthetic_holdout"):
            g = pd.read_parquet(truth)
            gamed = set(zip(g["dealer_id"], g["gamed_quarter"]))
        checks = {"timing rule (gaming_suspect)": k3.gaming_suspects(master, targets, "A"),
                  "keeper check, prompt read": k3.self_registration_suspects(master, targets, keepers,
                                                                             "keeper_date_prompt"),
                  "keeper check, late read": k3.self_registration_suspects(master, targets, keepers,
                                                                           "keeper_date_late")}
        for check, flagged in checks.items():
            f = {(d, str(q)) for d, q in flagged}
            hit = len(f & gamed)
            rows.append([f"{name} · {check}", len(f), hit, len(gamed) if gamed else "none",
                         f"{100 * hit / len(gamed):.1f}" if gamed else "",
                         f"{100 * hit / len(f):.1f}" if f and gamed else ""])
    OUT.write_text(f"""# X1 part 7b: the keeper check against the timing rule

_Generated by `leak1/selfreg.py`. Synthetic worlds; the register source is anchored on real RDW figures. These
measure the tool, not the group._

The unit is the A dealer-quarter. "Gamed" are the dealer-quarters the injector gamed (the truth); the red-team worlds
contain none of our gaming, so every flag there is a false alarm against gaming. The keeper check's parameters (a
quick change is 1 to 30 days; the prompt read) were fixed on our world before the holdout world was built.

{table(["world and check", "dealer-quarters flagged", "of which gamed", "gamed in the world", "recall (%)",
        "precision (%)"], rows)}
""")
    print(OUT.read_text().split("\n\n", 3)[-1])


if __name__ == "__main__":
    main()
